// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sksfaqdppvlsifeoqwyw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNrc2ZhcWRwcHZsc2lmZW9xd3l3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjQ0MDg3MTYsImV4cCI6MjA3OTk4NDcxNn0.Bj7kVwd9OzVl5l1sIx1LL59FpUoagwvEbS3kYU7rzFw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});